name: Hello World
  
on:
  issues:
    types: [opened, edited]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: hello_world
        id: hello_world
        run: |
          echo "Hello World!"
