name: Hello World
  
on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: hello_world
        id: hello_world
        run: |
          echo "Hello World!"
